### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'NoneType' objects

### ISSUE THREAD

**Issue by korroot** [LINBIT/linstor-client#1]
https://github.com/LINBIT/linstor-client/blob/973fa7bd3106173ef3b806c656438b045fe7662c/linstor/linstorapi.py#L984

It is not working when DisklessDriver has no driver defined in dict:
storage_pool_key_map '{'Lvm': 'LvmVg', 'Zfs': 'ZPool', 'Diskless': None, 'LvmThin': 'ThinPool'}'
driver name 'DisklessDriver'

Like 984 should cast to string:
return apiconsts.NAMESPC_STORAGE_DRIVER + '/' + str(cls._storage_pool_key_map[driver_name[:-len('Driver')]])

**Comment by raltnoeder** [comment]
Fix in progress

**Comment by rp-** [comment]
fixed in v0.2.0
