### ISSUE TITLE
linstor-client is not working without IPv6

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#13]
Hi, after upgrade to v0.9.9, linstor client is stopped working:

```
# linstor r l
Error: Unable connecting to linstor://localhost:3370: [Errno 99] Cannot assign requested address
```
see https://github.com/LINBIT/linstor-server/issues/51 for more details

**Comment by rp-** [comment]
Well this isn't a client problem, it can't work if there is nothing to connect to.

**Comment by kvaps** [comment]
Agree, client with non-IPv6 stack is working fine
