### ISSUE TITLE
Failed to create meta-data for DRBD volume while auto-placing

### ISSUE THREAD

**Issue by eleens** [LINBIT/linstor-client#23]
There occur the error with the message "Failed to create meta-data for DRBD volume"  When I create 16 volumes one time. But some volumes is normal.
This is the error report:
ERROR REPORT 5DAFBFD1-8EBCA-000103

============================================================

Application:                        LINBIT® LINSTOR
Module:                             Satellite
Version:                            1.0.1
Build ID:                           98a9905de43631b745c7c0741c2ef8f577513b23
Build time:                         2019-08-09T07:02:30+00:00
Error time:                         2019-10-28 17:19:21
Node:                               sto3

============================================================

Reported error:
===============

Description:
    Failed to create meta-data for DRBD volume rrd11/0

Category:                           LinStorException
Class name:                         VolumeException
Class canonical name:               com.linbit.linstor.storage.layer.exceptions.VolumeException
Generated at:                       Method 'createMetaData', Source file 'DrbdLayer.java', Line #781

Error message:                      Failed to create meta-data for DRBD volume rrd11/0

Error context:
    An error occurred while processing resource 'Node: 'sto3', Rsc: 'rrd11''

Call backtrace:

    Method                                   Native Class:Line number
    createMetaData                           N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:781
    adjustDrbd                               N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:432
    process                                  N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:260
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:683
    processResourcesAndTheirSnapshots        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:286
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:137
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:254
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:862
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:589
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:506
    run                                      N      java.lang.Thread:748

Caused by:
==========

Description:
    Execution of the external command 'drbdadm' failed.
Cause:
    The external command exited with error code 20.
Correction:
    - Check whether the external program is operating properly.
    - Check whether the command line is correct.
      Contact a system administrator or a developer if the command line is no longer valid
      for the installed version of the external program.
Additional information:
    The full command line executed was:
    drbdadm -vvv --max-peers 7 -- --force create-md rrd11/0

    The external command sent the following output data:
    drbdmeta 1011 v09 /dev/vvg1/rrd11_00000 internal create-md 7 --force

    The external command sent the following error information:
    lock on /usr/local/var/lock/drbd-147-1011 currently held by pid:31072
    lock on /usr/local/var/lock/drbd-147-1011 currently held by pid:31072
    Command 'drbdmeta 1011 v09 /dev/vvg1/rrd11_00000 internal create-md 7 --force' terminated with exit code 20

Category:                           LinStorException
Class name:                         ExtCmdFailedException
Class canonical name:               com.linbit.extproc.ExtCmdFailedException
Generated at:                       Method 'execute', Source file 'DrbdAdm.java', Line #495

Error message:                      The external command 'drbdadm' exited with error code 20

Call backtrace:

    Method                                   Native Class:Line number
    execute                                  N      com.linbit.linstor.storage.layer.adapter.drbd.utils.DrbdAdm:495
    simpleAdmCommand                         N      com.linbit.linstor.storage.layer.adapter.drbd.utils.DrbdAdm:440
    createMd                                 N      com.linbit.linstor.storage.layer.adapter.drbd.utils.DrbdAdm:221
    createMetaData                           N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:720
    adjustDrbd                               N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:432
    process                                  N      com.linbit.linstor.storage.layer.adapter.drbd.DrbdLayer:260
    process                                  N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:683
    processResourcesAndTheirSnapshots        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:286
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceHandlerImpl:137
    dispatchResources                        N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:254
    phaseDispatchDeviceHandlers              N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:862
    devMgrLoop                               N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:589
    run                                      N      com.linbit.linstor.core.devmgr.DeviceManagerImpl:506
    run                                      N      java.lang.Thread:748

END OF ERROR REPORT.

**Comment by ghernadi** [comment]
Hi, what is the version of drbd on that node? `cat /proc/drbd`

Although I don't think it is related, the current version of linstor if `1.2.0`, whereas you are still running `1.0.1`

**Comment by raltnoeder** [comment]
Also, what's the process that holds the lock (it said pid 31072)?

**Comment by rp-** [comment]
I'm pretty sure this isn't client related and we got no further info
