### ISSUE TITLE
--diskless deprecated, but --nvme-initiator or --drbd-diskless are not working

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#25]
```bash
# linstor r c m15c18 test -s diskless --drbd-diskless
ERROR:
Description:
    An unknown error occurred.
Details:
    No enum constant com.linbit.linstor.core.objects.Resource.Flags.DRBD_DISKLESS
Show reports:
    linstor error-reports show 5DE97984-00000-000091
```

```bash
# linstor r c m15c18 test -s diskless --nvme-initiator
ERROR:
Description:
    An unknown error occurred.
Details:
    No enum constant com.linbit.linstor.core.objects.Resource.Flags.NVME_INITIATOR
Show reports:
    linstor error-reports show 5DE97984-00000-000092
```

[5DE97984-00000-000091.log](https://github.com/LINBIT/linstor-client/files/3932036/5DE97984-00000-000091.log)
[5DE97984-00000-000092.log](https://github.com/LINBIT/linstor-client/files/3932037/5DE97984-00000-000092.log)

**Comment by ghernadi** [comment]
`--drbd-diskless` and `--nvme-initiator` flags will be included in the next linstor-server version. 
The patch for the client seems to be slipped through already in the current release.

Until linstor-server `1.4.0` is released, please use the old `--diskless` when creating a resource.
