### ISSUE TITLE
An unknown error occurred while setting controller config prop...

### ISSUE THREAD

**Issue by acidrop** [LINBIT/linstor-client#3]
Hello,

When setting controller drbd-options, I'm getting the following error..
Is this a bug or something wrong with the value? Seems to happen with other options as well.

linstor controller drbd-options --rcvbuf-size 2485760
ERROR:
    An unknown error occurred while setting controller config prop with key 'rcvbuf-size' in namespace 'DrbdOptions/Net' with value '2485760'.

linstor 0.6.1; GIT-hash: 695dda395fb9f25a4655f3d672059685f7fc7b39
linstor-satellite                    0.6.4-1
linstor-controller 0.6.4-1 

Thanks,
Yannis

**Comment by rp-** [comment]
Looks like a bug, because this works on my system.
Could you paste the controller log, there should probably even a error-report for that.

**Comment by acidrop** [comment]
Hi Rene,

Please find the controller log below..

http://paste.debian.net/1043056

Thanks
Yannis

**Comment by rp-** [comment]
Ok this is a bug, but there is a simple workaround for now.
Just remove your Controller node type from your setup.
You don't need to have it registered in your linstor setup, it is more for documentation purpose.
`linstor node delete <controller-name>`

**Comment by acidrop** [comment]
Yup, works now...

many thanks
Y
