### ISSUE TITLE
ModuleNotFoundError: No module named 'linstor'

### ISSUE THREAD

**Issue by chrstnwhlrt** [LINBIT/linstor-client#30]
Hi there,

evaluating linstor currently on a small raspberry 4 kubernetes test cluster using the ubuntu 19.10 arm64 release.

`linstor node create cluster-test-master 192.168.0.138 --node-type Combined`

leaves me with:

```
Traceback (most recent call last):
  File "/usr/bin/linstor", line 21, in <module>
    import linstor_client_main
  File "/usr/lib/python3/dist-packages/linstor_client_main.py", line 27, in <module>
    import linstor
ModuleNotFoundError: No module named 'linstor'
```

`dpkg -l | grep linstor`:

```
ii  linstor-client                   1.0.12-1ppa1~bionic1               all          Linstor client command line tool
ii  linstor-common                   1.4.2-1ppa1~bionic1                all          DRBD distributed resource management utility
ii  linstor-controller               1.4.2-1ppa1~bionic1                all          DRBD distributed resource management utility
ii  linstor-satellite                1.4.2-1ppa1~bionic1                all          DRBD distributed resource management utility
ii  python-linstor                   1.0.11-1ppa1~bionic1               all          Linstor python api library
```

A previous installation with armv7/32bit raspbian and a self compiled raspberry kernel just worked fine.
Using the ubuntu PPA:

`deb http://ppa.launchpad.net/linbit/linbit-drbd9-stack/ubuntu bionic main `

This could be related to https://github.com/LINBIT/linstor-client/issues/28

**Comment by rp-** [comment]
where is your linstorapi.py?
`find / -name linstorapi.py`

**Comment by chrstnwhlrt** [comment]
`find / -name linstorapi.py`:

`/usr/lib/python3.6/dist-packages/linstor/linstorapi.py`

**Comment by dimon222** [comment]
Seems like you got two pythons on system.
/usr/lib/python3/ vs /usr/lib/python3.6/

**Comment by rp-** [comment]
Just hit me that you are using a 19.10 ubuntu,
This will not work with our bionic PPA's, as 19.10 has probably something newer than python 3.6.
You will have to build packages yourself or install from source.

**Comment by chrstnwhlrt** [comment]
Thanks for the hint!
