### ISSUE TITLE
Feature request: LS_USER_CERTIFICATE, LS_USER_KEY, LS_ROOT_CA

### ISSUE THREAD

**Issue by kvaps** [LINBIT/linstor-client#35]
Hi, it would be really nice to support these environment variables out of box for linstor client as well for csi plugin (implemented in https://github.com/piraeusdatastore/linstor-csi/commit/eb0b344c51b52f6b8138d5a990d9a1f7aa8b4d5a)

**Comment by rp-** [comment]
next version will be able to set global args via environment variables prefixed with `LS_CLIENT_`

**Comment by rp-** [comment]
22e2b930d0c22b4022b088942df7d45c22515e21
