### ISSUE TITLE
Build from source code issue

### ISSUE THREAD

**Issue by Fredericwu** [LINBIT/linstor-client#38]
I downloaded the source code（V1.0.14  linstor-client-1.0.14.tar.gz） from the releases and encountered a problem during the build process，and then I did the same test in VV1.0.15 and also encountered the same error...
The operation process commands are as follows：
>>tar -zxvf  linstor-client-1.0.14.tar.gz
>>cd  linstor-client-1.0.14
>>make 
>>make install   ##fail，the reason for fail is as follows
![Screen Shot 2020-06-04 at 9 43 51 AM](https://user-images.githubusercontent.com/41657047/83705618-029e3400-a648-11ea-8b66-9e44d084deaa.png)

**Comment by rp-** [comment]
I fixed the install dependency in the Makefile.
