### ISSUE TITLE
`-r` does not filter snapshot list

### ISSUE THREAD

**Issue by chiraganand** [LINBIT/linstor-client#41]
Recently upgraded to using v1.2.1 and the following command does not work even though it is documented in the client: `$ linstor snapshot list -r resource-1`. The command ends up displaying all snapshots.

However, `-r` does filter everything else: `resource-definition list`, `volume-definition list`, and `resource list`.

**Comment by chiraganand** [comment]
Just tested `-n`, even this does not work as expected.

**Comment by kvaps** [comment]
@chiraganand what version of linstor-server do you have? Snapshots filtering was introduced in [`v1.7.0`](https://github.com/LINBIT/linstor-server/releases/tag/v1.7.0)

**Comment by chiraganand** [comment]
Using v1.6.2. Not sure if server upgrade is a possibility at the moment. Is there any workaround to this?

**Comment by ghernadi** [comment]
>  Is there any workaround to this?

sure, `grep` or even `jq` are your friends. Using `jq` you will want to use the machine readable output, like   
`linstor -m snapshot list | jq ...`

**Comment by kvaps** [comment]
As about OpenNebula driver, you can also consider using older version, example `v1.6.1`, the last version which uses classic curl for making requests, performs [snapshot listing](
https://github.com/OpenNebula/addon-linstor_un/blob/96dacdb9faef3e0c142bc7c03e4588416e461ae8/datastore/linstor_un/linstor_utils.sh#L236-L243) directly for the specific resource only.

**Comment by chiraganand** [comment]
> sure, `grep` or even `jq` are your friends. Using `jq` you will want to use the machine readable output, like
> `linstor -m snapshot list | jq ...`

Yes, the following works:
`linstor -m --output-version v0 snapshot list | jq -r ".[].snapshot_dfns[]? | select(.rsc_name == \"$RES\") | .snapshot_name"`

Thanks for the help.
