### ISSUE TITLE
Usability: bright yellow on white

### ISSUE THREAD

**Issue by candlerb** [LINBIT/linstor-client#45]
I run terminals with a white background.  Status values which are bright yellow are very hard to read:

![image](https://user-images.githubusercontent.com/44789/107927633-29e72800-6f6f-11eb-99b0-abd64900dc3d.png)

I realise I can turn off the coloring entirely with `--no-color`, but that has to be supplied on each command.  So I was wondering either:

1. Could `--no-color` be set via an enviroment variable?
2. Could a slightly darker color be used? `Color.BROWN` (which is really "dark yellow" in [ANSI terminal colors](https://www.lihaoyi.com/post/BuildyourownCommandLinewithANSIescapecodes.html#8-colors)) looks acceptable to me in both modes:

![image](https://user-images.githubusercontent.com/44789/107929798-11c4d800-6f72-11eb-9649-99fb6a4ddaa8.png)
![image](https://user-images.githubusercontent.com/44789/107929653-dcb88580-6f71-11eb-8782-eda188fc806c.png)

Tested using:

```
--- /usr/lib/python3/dist-packages/linstor_client/consts.py.orig	2021-01-13 09:56:42.000000000 +0000
+++ /usr/lib/python3/dist-packages/linstor_client/consts.py	2021-02-15 09:46:57.902526985 +0000
@@ -61,7 +61,7 @@
     (BLACK,
      DARKRE,
      DARKGREEN,
-     BROWN,
+     YELLOW,
      DARKBLUE,
      DARKPINK,
      TEAL,
@@ -69,7 +69,7 @@
      DARKGRAY,
      RED,
      GREEN,
-     YELLOW,
+     BRIGHTYELLOW,
      BLUE,
      PINK,
      TURQUOIS,
```

**Comment by rp-** [comment]
You can use a client config file with the `no-color` setting, e.g.:
```
[global]
no-color=
```

Otherwise, I would rather change your personal color theme and set a better readable yellow color, than changing yellow in the code, as for other users this would look totally different (depending on their used theme/colorscheme)

**Comment by candlerb** [comment]
Sure, I'm happy to do it that way - I wasn't aware it was possible.

There's no `linstor` manpage, but eventually I found in the `linstor-api-py` repo that the defaults file is `~/.config/linstor/linstor-client.conf` or `/etc/linstor/linstor-client.conf`.  That works with the setting you gave - thanks!

I also found that you can apply it via an [environment variable](https://github.com/LINBIT/linstor-client/blob/master/linstor_client_main.py#L265-L273). For `--no-color` it works as long as you give it an empty value.

```
root@node1:~# export LS_CLIENT_NO_COLOR=
root@node1:~# linstor v l
...
```
