### ISSUE TITLE
Proxmox 7 ModuleNotFoundError: No module named 'linstor'

### ISSUE THREAD

**Issue by Siya-Sharifi** [LINBIT/linstor-client#48]
Hi,

I installed a cluster of 4 Proxmox 7 and as written here was installed Linstor on Proxmox.

https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/

it shows but problem :

#linstor node list
Traceback (most recent call last):
File "/usr/bin/linstor", line 21, in
import linstor_client_main
File "/usr/lib/python3/dist-packages/linstor_client_main.py", line 27, in
import linstor
ModuleNotFoundError: No module named 'linstor'

#dpkg -l |grep linstor
ii linstor-client 1.9.0-1 all Linstor client command line tool
ii linstor-common 1.13.1-1 all DRBD distributed resource management utility
ii linstor-controller 1.13.1-1 all DRBD distributed resource management utility
ii linstor-proxmox 5.2.0-1 all DRBD distributed resource management utility
ii linstor-satellite 1.13.1-1 all DRBD distributed resource management utility
ii python-linstor 1.9.0-1 all Linstor python api library

whereis python

python: /usr/bin/python3.9 /usr/lib/python2.7 /usr/lib/python3.7 /usr/lib/python3.9 /etc/python3.9 /usr/local/lib/python3.9

#python3

python3 python3.9

Do you have an idea what's going on here?

**Comment by rck** [comment]
you probably enabled the `proxmox-6` repo on PVE7. Unfortunately we do not have a `proxmox-7` repo right now, but it should be available today/max tomorrow. Then you need to switch to that and (re)install the python components (`linstor-client`, `python-linstor`). Other versions (e.g., the ones in `proxmox-6`) are built for a different python version and as you saw will not work.

**Comment by Siya-Sharifi** [comment]
Thanks for fast feedback

Then I wait for new repo for proxmox 7 ...

best regards

**Comment by rck** [comment]
yes, that and the freshly released linstor-proxmox v5.2.1 should then be good enough to support PVE7.
