### ISSUE TITLE
Proxmox 7 LINSTOR high availability do not work

### ISSUE THREAD

**Issue by Siya-Sharifi** [LINBIT/linstor-client#49]
Hi,

I have built 4 Node Linstor Cluster and made it over [LINBIT](https://linbit.com/drbd-user-guide/linstor-guide-1_0-en/#s-linstor_ha) high availability.

Only if NODE01 is started Linstor Cluster is booted up, NODE01 will be out, it shows the error:

Error: Unable to connect to linstor://node01: [Errno 111] Connection refused
Error: Unable to connect to linstor://node02: [Errno 111] Connection refused
Error: Unable to connect to linstor://node03: [Errno 111] Connection refused
Error: Unable to connect to linstor://node04: [Errno 111] Connection refused

DNS is performed via / etc / hosts

on log is :
node01 Satellite[687]: 20:34:04.874 [DeviceManager] ERROR LINSTOR/Satellite - SYSTEM - Failed to write active loopback devices to /var/lib/linstor/loop_device_mapping.tmp [Report number 6106E8FD-14A1C-000001]

linstor nodes are COMBINED and cat /etc/drbd-reactor.d/linstor_db.toml
[[promoter]]
id = "linstor_db"
[promoter.resources.linstor_db]
start = ["var-lib-linstor.mount", "linstor-controller.service"]
 runner = systemd
 stop = []
 on-stop-failure = "echo b > /proc/sysrq-trigger"
 stop-services-on-exit = false

on all nodes are linstor-controller.service disabled. 

cat /etc/pve/storage.cfg
dir: local
        path /var/lib/vz
        content iso,vztmpl,backup

lvmthin: local-lvm
        thinpool data
        vgname pve
        content rootdir,images

drbd: drbdstorage
   content images,rootdir
   controller 10.10.10.11,10.10.10.12,10.10.10.13,10.10.10.14
   resourcegroup rScGrp_vdd
   preferlocal yes

more info:
linstor v l
╭─────────────────────────────────────────────────────────────────────────────────────────────────────╮
┊ Node   ┊ Resource   ┊ StoragePool ┊ VolNr ┊ MinorNr ┊ DeviceName    ┊ Allocated ┊ InUse  ┊    State ┊
╞═════════════════════════════════════════════════════════════════════════════════════════════════════╡
┊ node01 ┊ linstor_db ┊ vdd_pool    ┊     0 ┊    1001 ┊ /dev/drbd1001 ┊   204 MiB ┊ InUse  ┊ UpToDate ┊
┊ node02 ┊ linstor_db ┊ vdd_pool    ┊     0 ┊    1001 ┊ /dev/drbd1001 ┊   204 MiB ┊ Unused ┊ UpToDate ┊
┊ node03 ┊ linstor_db ┊ vdd_pool    ┊     0 ┊    1001 ┊ /dev/drbd1001 ┊   204 MiB ┊ Unused ┊ UpToDate ┊
┊ node04 ┊ linstor_db ┊ vdd_pool    ┊     0 ┊    1001 ┊ /dev/drbd1001 ┊   204 MiB ┊ Unused ┊ UpToDate ┊
┊ node01 ┊ vdd_rSc    ┊ vdd_pool    ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊ 90.02 GiB ┊ Unused ┊ UpToDate ┊
┊ node02 ┊ vdd_rSc    ┊ vdd_pool    ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊ 90.02 GiB ┊ Unused ┊ UpToDate ┊
┊ node03 ┊ vdd_rSc    ┊ vdd_pool    ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊ 90.02 GiB ┊ Unused ┊ UpToDate ┊
┊ node04 ┊ vdd_rSc    ┊ vdd_pool    ┊     0 ┊    1000 ┊ /dev/drbd1000 ┊ 90.02 GiB ┊ Unused ┊ UpToDate ┊

What can be wrong here?

**Comment by rck** [comment]
```
node01 Satellite[687]: 20:34:04.874 [DeviceManager] ERROR LINSTOR/Satellite - SYSTEM - Failed to write active loopback devices to /var/lib/linstor/loop_device_mapping.tmp [Report number 6106E8FD-14A1C-000001]
```

This one is a bug in the documentation. we need to change something in the linstor-satellite to not write to that (`chattr`ed) directory. Please remove that attribute (`chattr -i`) on all nodes for that (unmounted) directory until a new version of `linstor-satellite` is released.

Please check if that helps. Otherwise:
- you have `drbd-reactor` running on all nodes? with the same config?
- as the `linstor_db` volume is in use, I'd run `drbd-reactorctl status linstor_db` on that node and see if all services are started successfully. And if you then can run linstor commands like `linstor n l` on that node, but not on others then it is some DNS/client misconfiguration
- also note that the `linstor-client` has a different "where are my potential controllers" config than the linstor plugin. I would start with the client, and then the plugin.

**Comment by Siya-Sharifi** [comment]
Hi,

**on all Nodes are the same: and all clients became rebooted**
lsattr /var/lib/
--------------e------- /var/lib/linstor
--------------e------- /var/lib/linstor.orig
--------------e------- /var/lib/linstor.d

lsattr /var/lib/linstor /var/lib/linstor.orig /var/lib/linstor.d
--------------e------- /var/lib/linstor/linstordb.mv.db-2021-07-29T11:58+02:00.bak
--------------e------- /var/lib/linstor/lost+found
--------------e------- /var/lib/linstor/linstordb.mv.db
--------------e------- /var/lib/linstor/linstordb.mv.db.bak
--------------e------- /var/lib/linstor/linstordb.trace.db
--------------e------- /var/lib/linstor/loop_device_mapping
--------------e------- /var/lib/linstor/linstordb.mv.db-2021-07-29T11:44+02:00.bak
--------------e------- /var/lib/linstor.orig/loop_device_mapping
--------------e------- /var/lib/linstor.orig/linstordb.mv.db-2021-07-29T11:44+02:00.bak
--------------e------- /var/lib/linstor.orig/linstordb.mv.db-2021-07-29T11:58+02:00.bak
--------------e------- /var/lib/linstor.orig/linstordb.mv.db
--------------e------- /var/lib/linstor.orig/linstordb.trace.db
--------------e------- /var/lib/linstor.orig/linstordb.mv.db.bak
--------------e------- /var/lib/linstor.d/linstor_db.res
--------------e------- /var/lib/linstor.d/vdd_rSc.res

you have drbd-reactor running on all nodes? with the same config?
**yes drbd-reactor running on all nodes with the same config**

as the linstor_db volume is in use, I'd run drbd-reactorctl status linstor_db on that node and see if all services are started successfully. 
**only on Node01 are all service active as:** 
root@node01:~# drbd-reactorctl status linstor_db    
Promoter (ID: 'linstor_db')
Most likely active on this node
drbd-services@linstor_db.target
● ├─drbd-promote@linstor_db.service
● ├─linstor-controller.service
● └─var-lib-linstor.mount

**on other 2 to 4 Nodes i can run linstor commands like linstor n l**
for i in {2..4}; do ssh root@node0$i -- 'systemctl status drbd-reactor.service|grep -B2 -A2 Loaded' ; done
● drbd-reactor.service - DRBD-Reactor Service
     Loaded: loaded (/lib/systemd/system/drbd-reactor.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-02 10:49:56 CEST; 4min 27s ago
       Docs: man:drbd-reactor
● drbd-reactor.service - DRBD-Reactor Service
     Loaded: loaded (/lib/systemd/system/drbd-reactor.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-02 10:49:55 CEST; 4min 29s ago
       Docs: man:drbd-reactor
● drbd-reactor.service - DRBD-Reactor Service
     Loaded: loaded (/lib/systemd/system/drbd-reactor.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-02 10:49:55 CEST; 4min 29s ago
       Docs: man:drbd-reactor
root@node01:~# systemctl status drbd-reactor.service|grep -B2 -A2 Loaded
● drbd-reactor.service - DRBD-Reactor Service
     Loaded: loaded (/lib/systemd/system/drbd-reactor.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-02 10:33:02 CEST; 21min ago
       Docs: man:drbd-reactor

also note that the linstor-client has a different "where are my potential controllers" config than the linstor plugin. I would start with the client, and then the plugin.
**I did not understand what you mean by Linstor client and plugin, but the Linstor Configuration is here:**
dpkg -L linstor-client
/.
/etc
/etc/bash_completion.d
/etc/bash_completion.d/linstor
/usr
/usr/bin
/usr/bin/linstor
/usr/lib
/usr/lib/python3
/usr/lib/python3/dist-packages
/usr/lib/python3/dist-packages/linstor_client
/usr/lib/python3/dist-packages/linstor_client/__init__.py
/usr/lib/python3/dist-packages/linstor_client/argcomplete
/usr/lib/python3/dist-packages/linstor_client/argcomplete/__init__.py
/usr/lib/python3/dist-packages/linstor_client/argcomplete/_check_module.py
/usr/lib/python3/dist-packages/linstor_client/argcomplete/compat.py
/usr/lib/python3/dist-packages/linstor_client/argcomplete/completers.py
/usr/lib/python3/dist-packages/linstor_client/argcomplete/my_argparse.py
/usr/lib/python3/dist-packages/linstor_client/argcomplete/my_shlex.py
/usr/lib/python3/dist-packages/linstor_client/argparse
/usr/lib/python3/dist-packages/linstor_client/argparse/__init__.py
/usr/lib/python3/dist-packages/linstor_client/argparse/argparse.py
/usr/lib/python3/dist-packages/linstor_client/commands
/usr/lib/python3/dist-packages/linstor_client/commands/__init__.py
/usr/lib/python3/dist-packages/linstor_client/commands/advise.py
/usr/lib/python3/dist-packages/linstor_client/commands/commands.py
/usr/lib/python3/dist-packages/linstor_client/commands/controller_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/drbd_proxy_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/drbd_setup_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/error_report_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/exos_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/migrate_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/node_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/physical_storage_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/rsc_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/rsc_conn_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/rsc_dfn_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/rsc_grp_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/snapshot_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/storpool_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/vlm_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/vlm_dfn_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/vlm_grp_cmds.py
/usr/lib/python3/dist-packages/linstor_client/commands/zsh_completer.py
/usr/lib/python3/dist-packages/linstor_client/consts.py
/usr/lib/python3/dist-packages/linstor_client/consts_githash.py
/usr/lib/python3/dist-packages/linstor_client/table.py
/usr/lib/python3/dist-packages/linstor_client/tree.py
/usr/lib/python3/dist-packages/linstor_client/utils.py
/usr/lib/python3/dist-packages/linstor_client-1.9.0.egg-info
/usr/lib/python3/dist-packages/linstor_client-1.9.0.egg-info/PKG-INFO
/usr/lib/python3/dist-packages/linstor_client-1.9.0.egg-info/dependency_links.txt
/usr/lib/python3/dist-packages/linstor_client-1.9.0.egg-info/requires.txt
/usr/lib/python3/dist-packages/linstor_client-1.9.0.egg-info/top_level.txt
/usr/lib/python3/dist-packages/linstor_client_main.py
/usr/share
/usr/share/doc
/usr/share/doc/linstor-client
/usr/share/doc/linstor-client/changelog.Debian.gz
/usr/share/doc/linstor-client/copyright

Where should I change Linstor client config exactly?

**Comment by rck** [comment]
all the drbd-reactor stuff looks good, it is perfectly expected that one node (01 in your case) starts the controller successfully and the others already fail to even promote the linstor_db volume to Primary. All as expected:

Now you say that you can do `noot@node04:~# linstor n l`. How is that possible? Node04 does not run currently run linstor-controller (or you did not disable it), so how could that command succeed? Either it is running locally, which it should not (check `systemctl is-active linstor-controller`), OR you already told the linstor-client on node04 to connect to the linstor-controller on node01. Then I don't get why you ask you would configure the client? You can tell the local linstor-client which controllers to contact in multiple ways. via `--controllers='IP1,IP2'`, or via the `LS_CONTROLLERS` environment variable, or via `/etc/linstor/linstor-client.conf`:

```
[global]
controllers=IP1,IP2
```

and that is the linstor client. That is when you use `linstor` on the command line. And the plugin, configured via `/etc/pve/storage.cfg` is something completely different. That is the plugin. It does *not* use the linstor client (i.e., it does not call `linstor`), it talks to 1 or more controller via its settings in `storage.cfg`. And there you can also define multiple controllers. Which are then used by the plugin, and therefore by "proxmox" and commands like `pvesm`.

**Comment by Siya-Sharifi** [comment]
I've made some changes in clusters, HA cluster works only with about 30 to 90 seconds after failure of a node. If 2 nodes fail, because there are only 4 nodes, no more HA will work because of quorms. I think the requirement are at least 3 nodes.

I have run on all nodes chattr -i and changed the names in `/etc/linstor/linstor-client.conf` with IP.
[global]
Controllers = 10.20.20.12, 10.20.20.13,10.20.20.14,10.20.20.11

`rsync -avP /var/lib/linstor` to all nodes because all other nodes were empty and only Loop_Device_Mapping exists.

All nodes were rebooted.

After failure of a node, DRBD-Reactor is activated the Linstor controller on a node and all others are shown:

SystemCTL Status Linstor Controller.Service
● Linstor Controller.Service - Linstor Controller Service
     Loaded: loaded (/lib/systemd/system/linstor-controller.Service; Disabled; Vendor Preset: Enabled)
    Drop-in: /run/systemd/system/linstor-controller.service.d
             └─Reactor.conf
     Active: Inactive (Dead)

Aug 02 15:00:29 NODE03 SystemD [1]: Dependency Failed for Linstor Controller Service.
Aug 02 15:00:29 NODE03 SystemD [1]: Linstor Controller.Service: Job Linstor Controller.Service / Start Failed with Result 'Dependency'.

The Linstor client will need about 10 seconds to show on the node that takes over controller.

Thanks for your help
Best regards
