### ISSUE TITLE
'linstor vg list' and 'linstor s d -n <node>' won't work on latest version

### ISSUE THREAD

**Issue by acidrop** [LINBIT/linstor-client#54]
> ii  linstor-client                       1.16.0-1 
> ii  linstor-common                       1.20.2-1 
> ii  python-linstor                       1.16.0-1 

> LINSTOR ==> linstor vg l
> usage: linstor volume-group list [-h] [-p]
>                                  [-g {volumenr,flags} [{volumenr,flags} ...]]
>                                  [-R RESOURCES [RESOURCES ...]]
>                                  [-s SHOW_PROPS [SHOW_PROPS ...]]
>                                  name
> linstor volume-group list: error: too few arguments
> 
> Incorrect syntax. Use 'help vg' for more information:

> LINSTOR ==> linstor s l
> ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
> ┊ ResourceName  ┊ SnapshotName                        ┊ NodeNames              ┊ Volumes      ┊ CreatedOn           ┊ State      ┊
> ╞════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
> ┊ vm-100-disk-1 ┊ snap_vm-100-disk-1_autodaily221210  ┊ pve1, pve4             ┊ 0: 16.00 GiB ┊ 2022-12-10 17:00:07 ┊ Successful ┊
> ┊ vm-100-disk-1 ┊ snap_vm-100-disk-1_autodaily221211  ┊ pve1, pve4             ┊ 0: 16.00 GiB ┊ 2022-12-11 17:00:06 ┊ Successful ┊
> ┊ vm-100-disk-1 ┊ snap_vm-100-disk-1_autodaily221216  ┊ pve1, pve4             ┊ 0: 16.00 GiB ┊ 2022-12-16 17:00:31 ┊ Successful ┊
> ┊ vm-100-disk-1 ┊ snap_vm-100-disk-1_autodaily221217  ┊ pve1, pve4             ┊ 0: 16.00 GiB ┊ 2022-12-17 17:00:27 ┊ Successful ┊
> ┊ vm-100-disk-1 ┊ snap_vm-100-disk-1_autodaily221218  ┊ pve1, pve4             ┊ 0: 16.00 GiB ┊ 2022-12-18 17:00:13 ┊ Successful ┊
> ┊ vm-100-disk-1 ┊ snap_vm-100-disk-1_autoweekly221218 ┊ pve1, pve4             ┊ 0: 16.00 GiB ┊ 2022-12-18 09:00:14 ┊ Successful ┊
> ┊ vm-102-disk-2 ┊ snap_vm-102-disk-2_autodaily221210  ┊ pve1, pve2, pve3, pve5 ┊ 0: 10 GiB    ┊ 2022-12-10 14:00:16 ┊ Successful ┊
> ┊ vm-102-disk-2 ┊ snap_vm-102-disk-2_autodaily221211  ┊ pve1, pve2, pve3, pve5 ┊ 0: 10 GiB    ┊ 2022-12-11 14:00:09 ┊ Successful ┊
> ┊ vm-102-disk-2 ┊ snap_vm-102-disk-2_autodaily221217  ┊ pve1, pve2, pve3, pve5 ┊ 0: 10 GiB    ┊ 2022-12-17 14:00:12 ┊ Successful ┊
> ┊ vm-102-disk-2 ┊ snap_vm-102-disk-2_autodaily221218  ┊ pve1, pve2, pve3, pve5 ┊ 0: 10 GiB    ┊ 2022-12-18 14:00:08 ┊ Successful ┊
> ┊ vm-102-disk-2 ┊ snap_vm-102-disk-2_autodaily221219  ┊ pve1, pve2, pve3, pve5 ┊ 0: 10 GiB    ┊ 2022-12-19 14:00:08 ┊ Successful ┊
> ┊ vm-102-disk-2 ┊ snap_vm-102-disk-2_autoweekly221218 ┊ pve1, pve2, pve3, pve5 ┊ 0: 10 GiB    ┊ 2022-12-18 10:30:07 ┊ Successful ┊
> ┊ vm-104-disk-1 ┊ snap_vm-104-disk-1_autodaily221210  ┊ pve1, pve2             ┊ 0: 16.00 GiB ┊ 2022-12-10 15:00:08 ┊ Successful ┊
> ┊ vm-104-disk-1 ┊ snap_vm-104-disk-1_autodaily221216  ┊ pve1, pve2             ┊ 0: 16.00 GiB ┊ 2022-12-16 15:00:14 ┊ Successful ┊
> ┊ vm-104-disk-1 ┊ snap_vm-104-disk-1_autodaily221217  ┊ pve1, pve2             ┊ 0: 16.00 GiB ┊ 2022-12-17 15:00:10 ┊ Successful ┊
> ┊ vm-104-disk-1 ┊ snap_vm-104-disk-1_autodaily221218  ┊ pve1, pve2             ┊ 0: 16.00 GiB ┊ 2022-12-18 15:00:08 ┊ Successful ┊
> ┊ vm-104-disk-1 ┊ snap_vm-104-disk-1_autoweekly221218 ┊ pve1, pve2             ┊ 0: 16.00 GiB ┊ 2022-12-18 11:00:10 ┊ Successful ┊
> ┊ vm-106-disk-1 ┊ snap_vm-106-disk-1_autodaily221210  ┊ pve2, pve4             ┊ 0: 20 GiB    ┊ 2022-12-10 17:00:17 ┊ Successful ┊
> ┊ vm-106-disk-1 ┊ snap_vm-106-disk-1_autodaily221211  ┊ pve2, pve4             ┊ 0: 20 GiB    ┊ 2022-12-11 17:00:14 ┊ Successful ┊
> ┊ vm-106-disk-1 ┊ snap_vm-106-disk-1_autodaily221216  ┊ pve4, pve5             ┊ 0: 20 GiB    ┊ 2022-12-16 18:00:16 ┊ Successful ┊
> ┊ vm-106-disk-1 ┊ snap_vm-106-disk-1_autodaily221217  ┊ pve4, pve5             ┊ 0: 20 GiB    ┊ 2022-12-17 18:00:15 ┊ Successful ┊
> ┊ vm-106-disk-1 ┊ snap_vm-106-disk-1_autodaily221218  ┊ pve4, pve5             ┊ 0: 20 GiB    ┊ 2022-12-18 18:01:21 ┊ Successful ┊
> ┊ vm-106-disk-1 ┊ snap_vm-106-disk-1_autoweekly221218 ┊ pve4, pve5             ┊ 0: 20 GiB    ┊ 2022-12-18 08:00:15 ┊ Successful ┊
> ╰──────────────────────────────────────────────────────────────────────────────────

──────────────────────────────────────────────╯

> LINSTOR ==> linstor s d -n pve5 vm-102-disk-2 snap_vm-102-disk-2_autodaily221219
> usage: linstor snapshot delete [-h] [-n NODES [NODES ...]]
>                                resource_definition_name snapshot_name
> linstor snapshot delete: error: too few arguments
> 
> Incorrect syntax. Use 'help s' for more information:

**Comment by rp-** [comment]
`linstor vg list` always needed a resource group as argument, as volume groups are bound to resource-groups.

`linstor s d -n pve5 vm-102-disk-2 snap_vm-102-disk-2_autodaily221219` is a shortcoming of the used python argparse library. you can rearrange the arguments to get it work
`linstor s d vm-102-disk-2 snap_vm-102-disk-2_autodaily221219 -n pve5`
or use double `-`
`linstor s d -n pve5 -- vm-102-disk-2 snap_vm-102-disk-2_autodaily221219`
