### ISSUE TITLE
Installing LINSTOR Client from tarballs

### ISSUE THREAD

**Issue by tiptop-labs** [LINBIT/linstor-client#6]
What is the right procedure for installing LINSTOR Client from the tarballs provided by LINBIT? Should [linstor-client-0.9.2.tar](https://www.linbit.com/downloads/linstor/linstor-client-0.9.2.tar.gz) or [python-linstor-0.9.2.tar](python-linstor-0.9.2.tar) be used at the outset?

**Comment by rp-** [comment]
you need both.
python-linstor is the python library for linstor which is used by linstor-client.
Both are python projects so can be installed/build via the setup.py script

**Comment by tiptop-labs** [comment]
Thank you: running `make; make install` for both tarballs (`python-linstor-0.9.2.tar` first) now installed the client `/usr/local/bin/linstor`.
