### ISSUE TITLE
Satellite does not support the following layers: [DRBD]

### ISSUE THREAD

**Issue by tiptop-labs** [LINBIT/linstor-client#7]
I get the following error message when following approx. the example in the User's Guide and [auto-placing](https://docs.linbit.com/docs/users-guide-9.0/#s-linstor-new-volume) resources/volumes:

> ERROR:
> Description:
> Satellite 'node-2' does not support the following layers: [DRBD]

The kernel module for DRBD 9 is loaded on node-2. What is the reason for this error message and how can I rectify the root cause?

**Comment by rp-** [comment]
you probably don't have drbd correctly setup on that node.
check the satellite log and if drbd-utils and drbd9 kernel module is loaded

**Comment by anencore94** [comment]
This error seems to be occured when the user create node with wrong hostname on 'node create {hostname} {IP}' command.
I had the same error, but fix it by checking the hostname.

**Comment by IsaackRasmussen** [comment]
I've run into the same problem and I dont see any issues with my hostnames.

How do I verify kernel modules?
I presume for DRBD 9, I can run this: lsmod | grep -i drbd
Which gives me:
```
drbd                  528384  0
libcrc32c              16384  5 nf_conntrack,nf_nat,drbd,raid456,ip_vs

```
But what about drbd-utils ?

**Comment by ghernadi** [comment]
`drbdadm --version` or `cat /proc/drbd`

**Comment by IsaackRasmussen** [comment]
Thanks - the output also looks good to me
```
**drbdadm --version**
DRBDADM_BUILDTAG=GIT-hash:\ 147860216bf307433e2d0d7cfd6fad3642027b8d\ build\ by\ buildd@lgw01-amd64-060\,\ 2019-06-13\ 14:21:26
DRBDADM_API_VERSION=2
DRBD_KERNEL_VERSION_CODE=0x090013
DRBD_KERNEL_VERSION=9.0.19
DRBDADM_VERSION_CODE=0x090a00
DRBDADM_VERSION=9.10.0

**cat /proc/drbd**
version: 9.0.19-1 (api:2/proto:86-115)
GIT-hash: 6f5fa5d348a99e5eeb09d83c49853d72e614fd07 build by root@server013, 2019-08-26 13:26:53
Transports (api:16): tcp (9.0.19-1)

```

**Comment by ghernadi** [comment]
And the `uname -n` run on the satellite matches exactly the node name of the satellite?

**Comment by IsaackRasmussen** [comment]
Thanks for double-checking even though I claimed it was correct. I had not understood that the computer hostname had to match the linstor configured node name. Because it appeared to be communicating just fine.

Its working now - thanks again-

**Comment by raltnoeder** [comment]
To be more precise, the local node name must match the name of the node as it is registered in LINSTOR, because that name is used by LINSTOR to write DRBD configuration files, and DRBD requires the names in those configuration files to match that node's local node name.
