### ISSUE TITLE
Failed to create meta-data for DRBD volume while auto-placing

### ISSUE THREAD

**Issue by tiptop-labs** [LINBIT/linstor-client#9]
I try auto-place a resource on two nodes as follows:

    linstor node create node-1
    linstor node create node-2
    linstor storage-pool create lvm node-1 pool_lvm vg_linstor
    linstor storage-pool create lvm node-2 pool_lvm vg_linstor
    linstor resource-definition create test
    linstor volume-definition create test 1G
    linstor resource create test --auto-place 2 --storage-pool pool_lvm

As a result, the last command creates an LV in each of the two VGs `vg_linstor` but fails overall like this:

    ERROR:
    (Node: 'node-1') Failed to create meta-data for DRBD volume test/0
    ERROR:
    (Node: 'node-2') Failed to create meta-data for DRBD volume test/0

The error reports suggests there was an error when executing the external command `drbdadm -vvv --max-peers 7 -- --force create-md test/0`: `no resources defined!`.

Could it be that the problem is that I do not have DRBD configuration files present in `/etc/drbd.conf`, `/etc/drbd.d/`? So far, I have built the DRBD kernel module from [`drbd-9.0.17-1.tar.gz`](https://www.linbit.com/downloads/drbd/9.0/drbd-9.0.17-1.tar.gz) with `make` and then loaded the kernel model directly from the build.

**Comment by ghernadi** [comment]
> Could it be that the problem is that I do not have DRBD configuration files present in /etc/drbd.conf, /etc/drbd.d/?

Yep, you need to have `/etc/drbd.conf` which should contain something like 
```
include "drbd.d/global_common.conf";
include "drbd.d/*.res";
include "/var/lib/drbd.d/*.res";
```

Linstor makes sure to create `/etc/drbd.d/linstor-resources.res` if needed, which then will include all resources from `/var/lib/linstor.d/*.res` (this is where linstor will generate its `<resource_name>.res` files). But you still need to give DRBD an entry point where it should start looking for resource file as explained above.

**Comment by tiptop-labs** [comment]
Thanks, this brought me one step further: I have created `/etc/drbd.conf` with the first two `include` statements as well as a directory `/etc/dbrb.d/` and an empty `/etc/drbd.d/global_common.conf`.
Linstor now creates `/etc/drbd.d/linstor-resources.res` and `/var/lib/linstor.d/test.res`, but there is still an error when invoking the external command: `drbdadm -vvv --max-peers 7 -- --force create-md test/0`: `no resources defined!`.

`drbdadm` is not in my `PATH` for the installer placed it in `/usr/local/sbin/drbdadm`. And I have not restarted the DRBD kernel module since providing the configuration files. But I assume that is not what is causing the persisting issue. What else could I try?

**Comment by rck** [comment]
Sorry, but this - like the rest of your "issues" - is basic GNU/Linux admin stuff. None of that is in any way a issue/bug in the components you issued bugs for. LINBIT, the compony sponsoring the development of these components provides support/handholding (including ready made packages). But if you use the opensource components and compile yourself, we have to assume the most basic level of GNU/Linux system administration skills.

This is a development platform where you should file actual bugs, we do not consider it a support forum. Please ask such questions at the drbd-user mailing list, but please stop "spamming" the issue tracker. Thanks.
